apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pvcautoscaler.fullname" . }}
  labels:
    {{- include "pvcautoscaler.labels" . | nindent 4 }}
    {{- with .Values.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "pvcautoscaler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pvcautoscaler.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "pvcautoscaler.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
