apiVersion: v1
kind: Service
metadata:
  name: {{ include "pvcautoscaler.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "pvcautoscaler.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
