name: Go

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        check-latest: true
        cache-dependency-path: go.sum

    - name: Run fmt
      run: go fmt ./...

    - name: Run vet
      run: go vet ./...

    - name: Run test
      run: go test -v ./...

    - name: Run build
      run: go build -o bin/pvc-autoscaler ./cmd
